survey_name: pew_research_ATP_W92
# sum of weights = 10221.000322689664
# number of human respondents = 10916
# this file contains the weighted fraction of demographic groups for each demographic traits
# fractions are caluclated by ignoring nan values

trait_of_interest:
  - age_category_4
  - gender
  - education_level
  - income_level_category_13
  - race

target_distribution: # weighted demographic occupation fraction
    income: # used field: F_INC_SDT1. Note: there is another field F_INC_TIER2.
        source: income_level_category_13
        map_source:
            Less than $10,000: 0
            $10,000 to $19,999: 0
            $20,000 to $29,999: 0
            $30,000 to $39,999: 1
            $40,000 to $49,999: 2
            $50,000 to $59,999: 3
            $60,000 to $69,999: 4
            $70,000 to $79,999: 5
            $80,000 to $89,999: 6
            $90,000 to $99,999: 7
            $100,000 to $149,999: 8
            $150,000 to $199,999: 8
            $200,000 or more: 8
        map_survey:
            Less than $30,000: 0
            $30,000 to less than $40,000: 1
            $40,000 to less than $50,000: 2
            $50,000 to less than $60,000: 3
            $60,000 to less than $70,000: 4
            $70,000 to less than $80,000: 5
            $80,000 to less than $90,000: 6
            $90,000 to less than $100,000: 7
            $100,000 or more: 8
        survey_distribution:
            Less than $30,000: 0.2493283036707518
            $30,000 to less than $40,000: 0.12161630726421016
            $40,000 to less than $50,000: 0.0842846518610348
            $50,000 to less than $60,000: 0.09680423884037576
            $60,000 to less than $70,000: 0.06860417580674992
            $70,000 to less than $80,000: 0.06176021105303784
            $80,000 to less than $90,000: 0.04827236596750723
            $90,000 to less than $100,000: 0.05429481832461247
            $100,000 or more: 0.21503492721172007
    age: # used field: F_AGECAT
        source: age_category_4
        map_source:
            18-29: 0
            30-49: 1
            50-64: 2
            65 or Above: 3
        map_survey:
            18-29: 0
            30-49: 1
            50-64: 2
            65+: 3
        survey_distribution:
            18-29: 0.19135701370624675
            30-49: 0.33800433452724404
            50-64: 0.2559312675397847
            65+: 0.21470738422672442
    race: # used field: F_RACETHNMOD (Final Race and Ethnicity Modified). Note: there is another field F_RACECMB, F_HISP, F_HISP_ORIGIN
        source: race
        map_source:
            American Indian or Alaska Native: 4
            Asian or Asian American: 3
            Black or African American: 1
            Hispanic or Latino/a: 2
            Middle Eastern or North African: 4
            Native Hawaiian or Other Pacific Islander: 4
            White or European: 0
            Other: 4
        map_survey:
            White non-Hispanic: 0
            Black non-Hispanic: 1
            Hispanic: 2
            Asian non-Hispanic: 3
            Other: 4
        survey_distribution:
            White non-Hispanic: 0.6382962758191063
            Black non-Hispanic: 0.11672667765709145
            Hispanic: 0.16176289377061787
            Asian non-Hispanic: 0.05457958548990474
            Other: 0.02863456726327963
    # fields in F_RACECMB: White / Asian or Asian-American / Mixed Race / Or some other race / Balck or African-American / Refused / nan
    gender: # used field: F_GENDER
        source: gender
        map_source:
            Male: 0
            Female: 1
            Other (e.g., non-binary, trans): 2
        map_survey:
            A man: 0
            A woman: 1
            In some other way: 2
        survey_distribution:
            A man: 0.47139358312793167
            A woman: 0.5205920930153347
            In some other way: 0.008014323856733636
    education: # used field: F_EDUCCAT2. Note: there is another field F_EDUCCAT1
        source: education_level
        map_source:
            Less than high school: 0
            High school graduate or equivalent (e.g., GED): 1
            Some college, but no degree: 2
            Associate degree: 3
            Bachelor's degree: 4
            Professional degree (e.g., JD, MD): 5
            Master's degree: 5
            Doctoral degree: 5
        map_survey:
            Less than high school: 0
            High school graduate: 1
            Some college, no degree: 2
            Associate's degree: 3
            College graduate/some post grad: 4
            Postgraduate: 5
        survey_distribution:
            Less than high school: 0.0822000200685534
            High school graduate: 0.284877537722234
            Some college, no degree: 0.20902095722424782
            Associate's degree: 0.10114662356395968
            College graduate/some post grad: 0.1817685470848325
            Postgraduate: 0.14098631433617276
    region: # used field: F_CREGION
        source: region
        map_source:
            Northeast: 0
            Midwest: 1
            South: 2
            West: 3
        map_survey:
            Northeast: 0
            Midwest: 1
            South: 2
            West: 3
        survey_distribution:
            Northeast: 0.17280665945939438
            Midwest: 0.20823106030314914
            South: 0.3813099121145681
            West: 0.23765236812289792
    religion: # used field: F_RELIG. Note: there is another field F_RELIGCAT1
        source: religion
        map_source:
            Protestant: 0
            Roman Catholic: 1
            Mormon (Church of Jesus Christ of Latter-day Saints or LDS): 2
            Orthodox (such as Greek, Russian, or some other Orthodox church): 3
            Jewish: 4
            Muslim: 5
            Buddhist: 6
            Hindu: 7
            Atheist: 8
            Agnostic: 9
            Other: 10
            Nothing in particular: 11
        map_survey:
            Protestant: 0
            Roman Catholic: 1
            Mormon (Church of Jesus Christ of Latter-day Saints or LDS): 2
            Orthodox (such as Greek, Russian, or some other Orthodox church): 3
            Jewish: 4
            Muslim: 5
            Buddhist: 6
            Hindu: 7
            Atheist: 8
            Agnostic: 9
            Other: 10
            Nothing in particular: 11
        survey_distribution:
            Protestant: 0.42444438211315955
            Roman Catholic: 0.21078264786087306
            Mormon (Church of Jesus Christ of Latter-day Saints or LDS): 0.017228414840248528
            Orthodox (such as Greek, Russian, or some other Orthodox church): 0.006867780242474253
            Jewish: 0.0153430278425141
            Muslim: 0.006678416665898822
            Buddhist: 0.007912753836941526
            Hindu: 0.008874185544558317
            Atheist: 0.04524457407291312
            Agnostic: 0.057155896191790206
            Other: 0.02286175991202824
            Nothing in particular: 0.1766061608766004

political_affiliation: # used field: F_PARTY_FINAL
    source: PLEASE_FILL_IN
    map_source: PLEASE_FILL_IN
    map_survey:
        Democrat: 0
        Republican: 1
        Independent: 2
        Something else: 3
    survey_distribution:
        Democrat: 0.31275031591597946
        Republican: 0.251992813141028
        Independent: 0.28567943672902724
        Something else: 0.14957743421396522

ideology: # used field: F_IDEO
    source: PLEASE_FILL_IN
    map_source: PLEASE_FILL_IN
    map_survey:
        Very liberal: 0
        Liberal: 1
        Moderate: 2
        Conservative: 3
        Very conservative: 4
    survey_distribution:
        Very liberal: 0.07844320205777597
        Liberal: 0.18497606727784985
        Moderate: 0.40184469711157855
        Conservative: 0.2452975229347732
        Very conservative: 0.08943851061802226