religion:
  type: "multiple_choice"
  question: "What is your religion?"
  is_numerical: False
  choices:
    - "Protestant"
    - "Roman Catholic"
    - "Mormon (Church of Jesus Christ of Latter-day Saints or LDS)"
    - "Orthodox (such as Greek, Russian, or some other Orthodox church)"
    - "Jewish"
    - "Muslim"
    - "Buddhist"
    - "Hindu"
    - "Atheist"
    - "Agnostic"
    - "Other"
    - "Nothing in particular"
    - "Prefer not to answer"
  llm_parser_question: "What does the person's essay above mention about the religion of the person?"
region:
  type: "multiple_choice"
  question: "In which region of the United States do you live?"
  is_numerical: False
  choices:
    - "Northeast"
    - "Midwest"
    - "South"
    - "West"
    - "Prefer not to answer"
  llm_parser_question: "What does the person's essay above mention about the region of the United States the person lives in?"