defaults:
  - backstories: self_generated
  - llm_parameters: llama3_70b_vllm
  - _self_

# Set the output directory
hydra:
  run:
    dir: outputs/backstory_perplexity/${now:%Y-%m-%d}/${now:%H-%M-%S}

run_dir: ${hydra:runtime.output_dir}
save_dir: /rscratch/data/anthology/outputs/backstory_perplexity

# output data name
output_time_stamp: ${now:%Y-%m-%d}_${now:%H-%M-%S}
output_data_name: backstory_perplexity

# Debugging mode
debug: false

# Parallelization parameter
num_processes: 1

# The seed to use for the random number generator
random_seed: 42

# Frequency of saving the generated backstories
freq: 5