defaults:
  - questionnaire/ATP: ATP_W34_questions
  - special_prompt: consistency_prompt
  - format/mcq_symbol: uppercase
  - format/choice_format: curved_bracket
  - format/surveyor_respondent: question_answer
  - llm_parameters: llama3_70b_together
  - _self_

# Set ATP_WXX human survey data and demographics question data path
survey_data_path: /scratch/data/anthology/atp_data/ATP_W${wave}.sav
survey_demographics_metadata_path: /scratch/data/anthology/atp_data/ATP_W${wave}_demographic_questions.json
num_users: -1
prompt_style: qa

# Set the output directory
hydra:
  run:
    dir: outputs/ATP_W${wave}_baseline/${now:%Y-%m-%d}/${now:%H-%M-%S}

run_dir: ${hydra:runtime.output_dir}
save_dir: /scratch/data/anthology/outputs/ATP_W${wave}_baseline

# output data name
output_time_stamp: ${now:%Y-%m-%d}_${now:%H-%M-%S}
output_data_name: ATP_W${wave}_baseline

# Debugging mode
debug: false

# Parallelization parameter
num_processes: 1

# The seed to use for the random number generator
random_seed: 42

# Frequency of saving the generated backstories
freq: 5

wave: -1

include_compliance_forcing: true
number_compliance_forcing: 100

# include answer forcing prompt in the QA baseline prompt
include_answer_forcing: true

# demographic variables to include in the baseline prompt
trait_of_interest:
  - income
  - race
  - age
  - gender
  - education